#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

// Bindings are generated by build.rs into OUT_DIR.
// We include them here so downstream crates can depend on a normal Rust module.

include!(env!("KANAGAWA_PARSETREE_SYS_BINDINGS"));
