[package]
name = "kanagawa_typeck"
version = "0.1.0"
edition.workspace = true
description = "Type inference and checking for the Kanagawa compiler"

[dependencies]
kanagawa_hir = { path = "../kanagawa_hir" }
thiserror.workspace = true

[dev-dependencies]
kanagawa_syntax = { path = "../kanagawa_syntax" }
kanagawa_ast = { path = "../kanagawa_ast" }
